title: Wahlbrief - Briefwahl zur Landtagswahl beantragen
email: info@fragdenstaat.de
description: >-
  Jetzt die Unterlagen zur Briefwahl beantragen: Schnell, bequem und online. Wahlbrief erstellt in 2 Minuten den Online-Antrag.
baseurl: "/wahlbrief-website"
url: "https://wahlbrief.de/"
github_username: Wahlbrief

# Build settings
plugins:
  - jekyll-multiple-languages-plugin

languages: ["de", "en"]
defaultLang: de
exclude_from_localizations: ["assets"]
default_locale_in_subfolder: false

markdown: kramdown

bluesky: "https://bsky.app/profile/fragdenstaat.de"
linkedin: "https://www.linkedin.com/company/fragdenstaat/"
instagram: "https://www.instagram.com/fragdenstaat/"
imprint_url: "https://fragdenstaat.de/impressum/"
donate_url: "https://fragdenstaat.de/spenden/?pk_campaign=wahlbrief"